name: toolu_fatima

description: "A new Flutter project."



publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1



#-----------------------------PACKAGES-----------------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.2.2
  logger: ^2.4.0
  lottie: ^3.3.1
  connectivity_plus: ^6.1.2
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.2
  smooth_page_indicator: ^1.2.0+3
  intl_phone_field: ^3.1.0
  pinput: ^5.0.1
  smart_auth: ^3.2.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  wakelock_plus: ^1.2.10
  intl: ^0.20.2
  pdf: ^3.11.2
  open_file: ^3.5.10

  # Firebase
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.1




  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1


#----------------------------- / PACKAGES END -----------------------------------#




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  #-----------------------------LOCAL ASSETS-----------------------------------#
  assets:
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/user/
    - assets/images/payment_methods/
    - assets/images/payment_methods/
    - assets/icons/payment_success/
    - assets/logos/


  #-----------------------------LOCAL FONTS-----------------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
