// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-QfXqRzIfMCEeIgCUzdFvUK2mIGm8sf4',
    appId: '1:288366098562:web:3bf1e83b3de9aadf5bdc9b',
    messagingSenderId: '288366098562',
    projectId: 'louma-ae3ea',
    authDomain: 'louma-ae3ea.firebaseapp.com',
    storageBucket: 'louma-ae3ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqa_YX6_fXADPJwbDUGZ1Qj2GuA56uWm8',
    appId: '1:288366098562:android:884e2874c7bc37075bdc9b',
    messagingSenderId: '288366098562',
    projectId: 'louma-ae3ea',
    storageBucket: 'louma-ae3ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBved8rSZyqJMCDdsiDOP3Rh-Ii5S7_SUY',
    appId: '1:288366098562:ios:f4bc08db54f6b8a55bdc9b',
    messagingSenderId: '288366098562',
    projectId: 'louma-ae3ea',
    storageBucket: 'louma-ae3ea.firebasestorage.app',
    iosBundleId: 'com.kebedev.loumaOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBved8rSZyqJMCDdsiDOP3Rh-Ii5S7_SUY',
    appId: '1:288366098562:ios:f4bc08db54f6b8a55bdc9b',
    messagingSenderId: '288366098562',
    projectId: 'louma-ae3ea',
    storageBucket: 'louma-ae3ea.firebasestorage.app',
    iosBundleId: 'com.kebedev.loumaOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-QfXqRzIfMCEeIgCUzdFvUK2mIGm8sf4',
    appId: '1:288366098562:web:b92a86ff3aaeca935bdc9b',
    messagingSenderId: '288366098562',
    projectId: 'louma-ae3ea',
    authDomain: 'louma-ae3ea.firebaseapp.com',
    storageBucket: 'louma-ae3ea.firebasestorage.app',
  );

}